import { useMemo, useState } from 'react';
import { FileText, FileSpreadsheet, FileDown, Filter } from 'lucide-react';
import PageHeader from '@/components/ui/PageHeader';
import DataTable from '@/components/ui/DataTable';
import StatusBadge from '@/components/ui/StatusBadge';
import { demoReceipts, demoOffices, demoEmployees } from '@/lib/demoData';
import { toCsv, downloadFile } from '@/lib/export';
import { toastInfo } from '@/lib/toast';

export default function Reports() {
  const [filters, setFilters] = useState({ office: '', employee: '', from: '', to: '', status: '' });

  const filtered = useMemo(() => {
    return demoReceipts.filter((r) => {
      if (filters.office && r.office !== filters.office) return false;
      if (filters.employee && r.employee !== filters.employee) return false;
      if (filters.status && r.status !== filters.status) return false;
      if (filters.from && r.return_date < filters.from) return false;
      if (filters.to && r.return_date > filters.to) return false;
      return true;
    });
  }, [filters]);

  const exportColumns = [
    { key: 'receipt_number', header: 'Receipt Number' },
    { key: 'employee', header: 'Employee' },
    { key: 'office', header: 'Office' },
    { key: 'return_date', header: 'Return Date' },
    { key: 'items', header: 'Items' },
    { key: 'status', header: 'Status' },
  ];

  const exportCsv = () => downloadFile('rreps-report.csv', toCsv(exportColumns, filtered));
  const exportExcel = () =>
    // Excel opens CSV natively; a true .xlsx needs a backend/library (backend phase).
    downloadFile('rreps-report.xls', toCsv(exportColumns, filtered), 'application/vnd.ms-excel');
  const exportPdf = () => toastInfo('PDF export is generated by the backend (with blockchain metadata) — coming in the API phase.');

  const set = (k) => (e) => setFilters((f) => ({ ...f, [k]: e.target.value }));

  const tableColumns = [
    { key: 'receipt_number', header: 'Receipt No.', render: (r) => <span className="font-medium text-primary">{r.receipt_number}</span> },
    { key: 'employee', header: 'Employee' },
    { key: 'office', header: 'Office', className: 'text-slate-500 dark:text-slate-400' },
    { key: 'return_date', header: 'Date', className: 'tabular-nums text-slate-500 dark:text-slate-400' },
    { key: 'items', header: 'Items', className: 'tabular-nums text-slate-500 dark:text-slate-400' },
    { key: 'status', header: 'Status', render: (r) => <StatusBadge status={r.status} /> },
  ];

  return (
    <div className="space-y-5">
      <PageHeader
        title="Reports"
        subtitle="Filter return receipts and export the results."
        actions={
          <div className="flex flex-wrap gap-2">
            <button onClick={exportCsv} className="btn-secondary"><FileDown className="h-4 w-4" />CSV</button>
            <button onClick={exportExcel} className="btn-secondary"><FileSpreadsheet className="h-4 w-4" />Excel</button>
            <button onClick={exportPdf} className="btn-secondary"><FileText className="h-4 w-4" />PDF</button>
          </div>
        }
      />

      {/* Filters */}
      <div className="card p-4">
        <div className="mb-3 flex items-center gap-2 text-sm font-semibold text-slate-600 dark:text-slate-300">
          <Filter className="h-4 w-4" /> Filters
        </div>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-5">
          <div>
            <label className="label">Office</label>
            <select className="input" value={filters.office} onChange={set('office')}>
              <option value="">All</option>
              {demoOffices.map((o) => <option key={o.id} value={o.office_name}>{o.office_name}</option>)}
            </select>
          </div>
          <div>
            <label className="label">Employee</label>
            <select className="input" value={filters.employee} onChange={set('employee')}>
              <option value="">All</option>
              {demoEmployees.map((e) => <option key={e.id} value={e.full_name}>{e.full_name}</option>)}
            </select>
          </div>
          <div>
            <label className="label">From</label>
            <input type="date" className="input" value={filters.from} onChange={set('from')} />
          </div>
          <div>
            <label className="label">To</label>
            <input type="date" className="input" value={filters.to} onChange={set('to')} />
          </div>
          <div>
            <label className="label">Status</label>
            <select className="input" value={filters.status} onChange={set('status')}>
              <option value="">All</option>
              <option value="blockchain_verified">Verified</option>
              <option value="blockchain_pending">Pending</option>
              <option value="submitted">Submitted</option>
              <option value="draft">Draft</option>
            </select>
          </div>
        </div>
      </div>

      <p className="text-sm text-slate-500 dark:text-slate-400">{filtered.length} result(s)</p>
      <DataTable columns={tableColumns} rows={filtered} searchable={false} emptyTitle="No results" emptyMessage="Adjust the filters above." />
    </div>
  );
}
